export const LIMITS = {
  MAX_IMAGE_SIZE_MB: 5,
  MAX_IMAGES_PER_PRODUCT: 5,
  MAX_PRODUCT_TITLE_LENGTH: 100,
  MAX_PRODUCT_DESCRIPTION_LENGTH: 1000,
  MAX_RADIUS_KM: 10,
  DEFAULT_RADIUS_KM: 2,
  PRODUCTS_PER_PAGE: 20,
  CHAT_MESSAGES_PER_PAGE: 50,
  MAX_RECENT_SEARCHES: 5,
  OTP_LENGTH: 6,
  PHONE_LENGTH: 11,
};
